#make client
#./tcpEchoClient
#make server
#./tcpthreadserver
#client: 20201118_TCPthread_Client.c
#	gcc -o tcpthreadclient 20201118_TCPthread_Client.c
server: 20201118_TCPthread_Server.c
	gcc -o tcpthreadserver 20201118_TCPthread_Server.c -lpthread
